import './styles/reset.css'
import './styles/globals.scss'
import './styles/mixin.scss'
import './styles/font.scss'
import { Inter } from 'next/font/google'
import Header from './components/header.js'
import Footer from './components/footer.js'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
